# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

after_success:
  - npm run travis-update

env:
  global:

    # DOC_SEARCH_ID & DOC_SEARCH_KEY
    - secure: "Jjq86BkxLcYQcw8V12p01Jd+X9pZD4aZL8ILzGFp0FBEqJRtgpIJe57Z5zB/gkZxAfrgZxKW3SaFMy8OizGPnA7xO0AYyH/KDv3P/xGlGbV8VtAHLvrA/WI2NNZSQf8c+UEBqK4ZiXrbkI62xlEED6WxRrqXSBGhYKZhXI7EsCSxdMW6+19IeiolNSpKL3CExglS7p7UzGSE+BIRZWmo5ya4bMkahR2Q5yoY3wAc2FKb4KWCH55bF/0crRDbCAw5Nvp1YVGT2EnHuBHck0Z5Hwy+/5LUOYB3uLNXUqfsRRkIQA653/01l18BNCQfO2mtFeNKjah51+BoZkMUAo4+1ebWTt0R0l5M3qKfrjUDxD8FJNYLMx20Vx8xx1LRrQzwXagB7J8OZ8LciYcbJWH86nQnSI9AOAQgc7f07CM/alTq2b8sPY1rgf9l8rx2Sj+jgPsFOlNOrYxQnQSLtiEjepAoYaW0a/FLyWBSyVXYgi6QpVGbv2OOCJl+9bcZUY+P8KynN1jwrmXv2eTDCwpy/5y4Uw6+4s7p/p5CyfboMZZ0Qq6dk4r3QlWr+tw7eGwmEswS93J3D58CjpMStlxEygDFA9gV8Y72woQAV2VbS7DjDsYsD4+W7FIfSqdL8ATj/hOrSUkyQJAAtsDSmVo/pc8+KRBOuc5G7rbaCKpN9J4="

    # GH_USER_EMAIL & GH_USER_NAME
    - secure: "eFYQUR5b7vA7Q/kLiabHG5Qldy024n3ARdcEY+vVWMOWi1dAbxFj9/gv0qIxkxzsSdr6yUmG6gjfusows3BbJP56SttFambN5WQcv1gK3m/urtC2v1fFMkKAAd1eDgEkEQXZRN8TeqXpu1RPyYctUiSm6JZ82ah0vNxPXJ9+E3nMv76Ok/tJ2DOO7BUMb4GXGxa0G9lta/M5LHiHMB9IP5vePEO02IrbAzXYgBrLlUp5LwPpugLvijR1gYo+NQvgUy2Zyo5t9YhNAQPfps/C3OfyRHvIc2+hZE12xtBE1M1iTOFBuCKmT9BInbq6tTbjJLOIyaFgfV2So/H0yiegilyFfazqeRN3sVCanUiG7jB2cPQlLvxwjRZvuWXD5uhSwiImzMSmzEEfLDydBj5ZQf941scH1h0s716DHV0G6wsQvu2LZeWrGsz+Mn5ApYKCnd9Ifa9K2mQ5k4JkUzh850PIjzwQE2THYW4uhHcdXgwpoWlQjIqbXue0paYxbgGaXS0IwLNw3sUfh3hIRQmxuPFxvwzD4+NkmxhjvUpAxgPD0t8tvrhhgpPeZ+c5IXKRdOA0jdtzSR9JB1l2CigmTu9gIeTqImGLNaA8pmfvUK0VS5r5jRcsFVDttZ1B745lC2t1vt9LlMJa5xUFehF6bzi9MS6VNo4+aOcc32vkKSc="

language: node_js

node_js: lts/*

notifications:
  email:
    on_failure: always
    on_success: never
