# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

after_success:
  - npm run update-website-branch

env:
  global:
    - secure: "hD8/KCioPgu8h+XIiY+a8KhEB+cHlQuOb/9y4eVBR6E7Xap4se52EMU3+8rqx6V5bXNMrex+bZ+YoZ3MYm79hBB+T5XJyEfVIXIao0r0g5wI0vj6w1HpUgEL3cqXzrijKya3X+YZ6I8j0kX4ogInnL7/hOWQhbWWELhvUchiES5Q4vLuzaSqPjg0ZwrSt+q9xEDh+tGbKHvN9nvDShAGqUJ8UAfGqI4W6pOtvMq6hbopAFEuxy1GX+DZY6U4uMdjp7oqt1aIzL5VFmM5nuoFFyYtF2FhBve/WRt1sNmIrC64bLaEre8Esth8Gq1Fa6q0/jSC1t2Emh0riJD111gpwNkA8GfsApfBfrBAteXLESyTTP9FGuhp9MbUL+qEGzc7Dd9sluSGGMn67f8lHDHhRvVEYpbNzBHkjTL+imHh4moW4xHyDQ1pGvVPRjxzWwCy8m4WQEI9wS7Qjh2PcME+RdYA9/VQZLBmTFTPmah5RbsOHj7VDBHDjJaG5dHGsmc+T6SvLJngS3MRWbi8bKU7iHISM6zNqwiCcLtDOef4sHDbnOlMRQe7NFo3PWJzi36hx0AXHBM/jGP9IM/aw+SGsKjsABkmCRdPOmuQbKuyBO61MXt503Ogn4ftt+EpHNG7sbe/SjngTG8f6F/vB8+qNextpJ9dTNeyqcg8WnX0RNg="

language: node_js

dist: trusty

node_js:
  - node

notifications:
  email:
    on_failure: always
    on_success: never
