# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

env:
  global:

    # DOC_SEARCH_ID & DOC_SEARCH_KEY
    - secure: "Jjq86BkxLcYQcw8V12p01Jd+X9pZD4aZL8ILzGFp0FBEqJRtgpIJe57Z5zB/gkZxAfrgZxKW3SaFMy8OizGPnA7xO0AYyH/KDv3P/xGlGbV8VtAHLvrA/WI2NNZSQf8c+UEBqK4ZiXrbkI62xlEED6WxRrqXSBGhYKZhXI7EsCSxdMW6+19IeiolNSpKL3CExglS7p7UzGSE+BIRZWmo5ya4bMkahR2Q5yoY3wAc2FKb4KWCH55bF/0crRDbCAw5Nvp1YVGT2EnHuBHck0Z5Hwy+/5LUOYB3uLNXUqfsRRkIQA653/01l18BNCQfO2mtFeNKjah51+BoZkMUAo4+1ebWTt0R0l5M3qKfrjUDxD8FJNYLMx20Vx8xx1LRrQzwXagB7J8OZ8LciYcbJWH86nQnSI9AOAQgc7f07CM/alTq2b8sPY1rgf9l8rx2Sj+jgPsFOlNOrYxQnQSLtiEjepAoYaW0a/FLyWBSyVXYgi6QpVGbv2OOCJl+9bcZUY+P8KynN1jwrmXv2eTDCwpy/5y4Uw6+4s7p/p5CyfboMZZ0Qq6dk4r3QlWr+tw7eGwmEswS93J3D58CjpMStlxEygDFA9gV8Y72woQAV2VbS7DjDsYsD4+W7FIfSqdL8ATj/hOrSUkyQJAAtsDSmVo/pc8+KRBOuc5G7rbaCKpN9J4="

    # AZURE_WA_USERNAME, AZURE_WA_PASSWORD, AZURE_WA_SITE, AZURE_WA_SLOT
    - secure: "Bx6tfqQJYjlSofs3wEr2iqWx75HuR+Qtybomc97ueGxlkHjCXKF2A7one9ykwm+EVdJGVPLKM4bvS2ebqeNSPFSNyZbajXLV24lXgXsA3UVsXI3kBDkKG/bouyuQWvCeYAKF1XSbQM3513XbYSDWCdO72IkB5E961nvKCkLcsvJ+WGeE+3YtigK8ThHlzcM9Twt22y7ZQa4Y429uR6I1tAYzYkp4XHG/SO0tb9SAdGDg+nwkpyXq50HG1DSYOU+Q2x+Hpebz7gg9VckBLslicWp7qVkCKRS9VQAlacTLTVfQopxjC3gy0uNYOSDOle7RRomi9uYs3u4TPdW5Q2mkQJuFv2j/zaU7/tOTV+JEEaexA1gDFCH9NANCAHkgTeBLVerMINfFDrlj7qjIEoPZfhS1wxWZIeNGa3jGqdOLj02jBjJYUWmhdcwh61DUnYmYoErU5f2fG/K6mfbAr6e9F7MsYWFB3Q2GGEwIIUQUBqCD+7J+r/7CZoItqdad6fzvUzbUzaI4UPPSjhQJqApYF+XDfgeiFe24OmQtvUjHF/Ic7jeTwhAVXviAAbO29w8IuYX95XoOZBzDAJ8xXmdlvV2JHPhlmde18Bd3Q0Q7TlkKx/D8Ok+Cfx3o9Z4BRcfKfr75Ivc9gBZ3pWAocwS1uXCS2C0C+kmb6toSq5ffsq8="

    # AZURE_SERVICE_PRINCIPAL, AZURE_SERVICE_PRINCIPAL_PASSWORD, AZURE_TENANT
    secure: "X/QMPB9/T31/sVQdiuzAgMlK2/Cc4koyom/CH1yUVyL+u8zYj4N+GF2yrI+aH0nw5LjgN44ENvz5Of945MGGpGiCYCXRzuZZhitQrfGVoW/97je6P0TrcCMzMtluBRs6gvq7XkWyl7hIUsYvFBnUiyr7AhdrN5OHYzbKJuuyB4T0EefyCfDyyKcytEiUlfaIyXa1TOOraEso4t9ghp+54kcUwrNTGtSUiDIy/XBb9PQkf2nJobm2O1F1b+UJvyHURWB4LOv758q8Apc/MIo7NSbSgOODCMQaRVPn1m3ZD+8EsAfNjjeSOO4OZlTO/tr1EzC/zv0Ib7czdtsDAEjDqkr3naKg2BCF1HHDYQ7alH7FOIA8cz8EKgmBx7keYnUaWVucX2gHsEZCMo0cPaUJxHAWhEekPG2iswzbvZhdWHdQdH9+GTUtN5r6oCL0MNDMHT04C2IgWHR8DFlT9kTDz4eojc3pjoU+pciWDRXC8NATM6orJrG7cAII9/queBlTVfa+BTtyHbL8jiHHQmEDnv3TwE/DIYY3Nwf2Zaw9YL/nPlKtEqQKl49dE51gYfT/BhzO8c3nRjOH6Vwep289H5IIQhfyTCilzV6wnFDu06iiINDpveP350LMQKNbPNHySJVBFdbSS88sAjorFbfpX0lqUFB07i/sjbQkZwwmP+U="

    # GIT_USER_EMAIL, GIT_USER_NAME, GIT_PASSWORD
    secure: "OINn8LhTK6hTngwlxjum3k6Zuh08vfqSFbVhkNZnE9VlSZ+B3my1mmVSQYYBfo3lZXfEtiFuweVOIR/1Eh6FUK5r5+dGrNdg61I8eOhY4iVpNmaePTp6CdcHduVWAYolJEcbb//45FlLZAbEDXPVClg1By2fgOqg6RMHxIOZwSb4SFKCq4EXqjS3LNYhxUva+pUGhxxp1fEcX/vBz38HYar+JpSqZ/WO19RPaYOdXBfPCCLIgEYvtrEylupRVKybqL9rCzY1dZ9lipdrtm4Whs141RqHj7yxg1iyA+Qa9T9NqTOilVl349W9Bf24mt5p58iP0h3zc3HWK197Kwf8EJsSat5CnzXRRGM636FrrxlYol6QKyEa7IDolvJVryKT5mOE/2rwdPkdfteXm3IK3h49hniXR72eNO5oNFaNsrKp6w+LM4mu4q3XxXdloJr+26wc1BptRRU4XJrg4Qvdlx19ALkbu93mo1eW+aabKJeAnMj53LV7h4JSQqITP/DQWJRaKu9Zu4JHQHsZ4VnoyOqvf+OojO4fpWs/2YnyxIeOMYDB5EScBPljWPF2BDQFwqaJDN5DZegLWXx6XssZ2ObryfHPUNAlZ0spU5Jb0+O84LVvgf0RIgwIAChZww/I27/EFdcwt9woVdvRi/ViinydbZHa9vyUA9imG2NSRMo="

script:
  - npm test

after_success:
  - npm run travis-update
  - npm run test-staging

after_script:
  - npm run swap

language: node_js

node_js: lts/*

notifications:
  email:
    on_failure: always
    on_success: never
