# Scope the validations to master and PRs to master
trigger:
  - master
pr:
  - master

# We have one single job with conditional steps for changes in master
jobs:
- job: 'webhintio'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: npm install
    displayName: 'Install dependencies'
  - script: npm test
    displayName: 'Test'
  - script: ./helpers/update-site.sh
    displayName: 'Deploy'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    env:
      GIT_USER_EMAIL: $(GIT_USER_EMAIL)
      GIT_USER_NAME: $(GIT_USER_NAME)
      GIT_PASSWORD: $(GIT_PASSWORD)
  - script: npm run test-staging && node helpers/integration-tests/index.js
    displayName: 'Analyze staging with webhint'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  - bash: |
      az login --service-principal -u $AZURE_SERVICE_PRINCIPAL -p $AZURE_SERVICE_PRINCIPAL_PASSWORD --tenant $AZURE_TENANT
      az webapp deployment slot swap -g webhint-web -n sonarwhal --slot staging
    displayName: 'Swap into production'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    env:
      AZURE_SERVICE_PRINCIPAL: $(AZURE_SERVICE_PRINCIPAL)
      AZURE_SERVICE_PRINCIPAL_PASSWORD: $(AZURE_SERVICE_PRINCIPAL_PASSWORD)
      AZURE_TENANT: $(AZURE_TENANT)
  - bash: |
      curl https://www.google.com/ping?sitemap=https://webhint.io/sitemap.xml
      curl https://www.bing.com/ping?sitemap=https://webhint.io/sitemap.xml
    displayName: 'Update sitemaps'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- job: 'Algolia'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
    - script: npm run ci-docsearch-scraper
  condition: eq(variables['Build.Reason'], 'Schedule')
